name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  robot_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./robot

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Robot Framework and other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        mkdir -p robot_output
        robot --outputdir robot_output tests/suites/api_test_suite.robot
      continue-on-error: true

    - name: Publish Robot Framework output
      uses: actions/upload-artifact@v2
      with:
        name: robot-output
        path: robot_output/

    - name: Extract and print Robot Framework results
      id: extract_robot_results
      run: |
        total_tests=$(xmllint --xpath 'string(/robot/statistics/total/stat[@name="All tests"]/@total)' robot_output/output.xml)
        passed_tests=$(xmllint --xpath 'string(/robot/statistics/total/stat[@name="All tests"]/@pass)' robot_output/output.xml)
        failed_tests=$(xmllint --xpath 'string(/robot/statistics/total/stat[@name="All tests"]/@fail)' robot_output/output.xml)
        echo "Total tests: $total_tests"
        echo "Passed tests: $passed_tests"
        echo "Failed tests: $failed_tests"
        echo "::set-output name=total_tests::$total_tests"
        echo "::set-output name=passed_tests::$passed_tests"
        echo "::set-output name=failed_tests::$failed_tests"

    - name: Comment on the PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Test Results
          - **Total tests:** ${{ steps.extract_robot_results.outputs.total_tests }}
          - **Passed tests:** ${{ steps.extract_robot_results.outputs.passed_tests }}
          - **Failed tests:** ${{ steps.extract_robot_results.outputs.failed_tests }}