name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  robot_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./robot

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Robot Framework and other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Robot Framework tests
    #   run: |
    #     mkdir -p robot_output
    #     robot --outputdir robot_output tests/suites/api_test_suite.robot
    #   continue-on-error: true

    # - name: Publish Robot Framework output
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: robot-output
    #     path: robot_output/

    - name: Extract and print Robot Framework results
      id: extract_robot_results
      run: |
              python -m robot tests/suites/api_test_suite.robot

              python -c "
              import os
              import xml.etree.ElementTree as ET
              tree = ET.parse('output.xml')
              root = tree.getroot()
              total_tests_elem = root.find('.//total/stat[@name=\"All tests\"]')
              total_tests = total_tests_elem.get('total') if total_tests_elem is not None else '0'
              passed_tests = total_tests_elem.get('pass') if total_tests_elem is not None else '0'
              failed_tests = total_tests_elem.get('fail') if total_tests_elem is not None else '0'
              print(f'Total tests: {total_tests}')
              print(f'Passed tests: {passed_tests}')
              print(f'Failed tests: {failed_tests}')
              with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                  env_file.write(f'TOTAL_TESTS={total_tests}\n')
                  env_file.write(f'PASSED_TESTS={passed_tests}\n')
                  env_file.write(f'FAILED_TESTS={failed_tests}\n')
                      "

    - name: Comment on the PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Integration Test Results
          - **Total tests:** ${{ steps.extract_robot_results.outputs.total_tests }}
          - **Passed tests:** ${{ steps.extract_robot_results.outputs.passed_tests }}
          - **Failed tests:** ${{ steps.extract_robot_results.outputs.failed_tests }}