name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  robot_test:
    name: Robot Integration Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./robot

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Robot Framework and other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
              python -m robot tests/suites/api_test_suite.robot

              python -c "
              import os
              import xml.etree.ElementTree as ET

              root = ET.parse('output.xml')
              results = []
              for stat in root.findall('.//stat'):
                  pass_count = stat.get('pass')
                  fail_count = stat.get('fail')
                  skip_count = stat.get('skip')
                  results.append({'pass': pass_count, 'fail': fail_count, 'skip': skip_count})

              print(f'Skiped tests: {skip_count}')
              print(f'Passed tests: {pass_count}')
              print(f'Failed tests: {fail_count}')

              with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                  env_file.write(f'SKIPED_TESTS={skip_count}\n')
                  env_file.write(f'PASSED_TESTS={pass_count}\n')
                  env_file.write(f'FAILED_TESTS={fail_count}\n')
                      "

    - name: Comment on the PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Integration Test Results
          - **Skiped tests:** ${{ env.SKIPED_TESTS }}
          - **Passed tests:** ${{ env.PASSED_TESTS }}
          - **Failed tests:** ${{ env.FAILED_TESTS }}