name: Owasp ZAP Scan

on: 
  workflow_dispatch:
  workflow_run:
    branches: ['main']
    workflows: ['integration-test']
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ vars.APP_COSTUMER_URL }}