name: Owasp ZAP Scan

on: 
  workflow_run:
    workflows: ["integration-test"]
    types:
      - completed
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ vars.APP_COSTUMER_URL }}
          cmd_options: '-a'